chore: add darwin/arm64 prebuild support
ChainSafe/blst-ts pull request #113
Opened 2024-02-02 16:21 UTC by jeluard

A new [macos runner](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) has been released. This image runs on M1 architecture, allowing to create `prebuilds` for `darwin/arm64`.

2024-02-02 16:23 UTC, jeluard commented on .github/workflows/main.yml
> +        node: [16, 17, 18, 20]
Node `14` is not available on this new image. As it's pretty old now (node `20` is the LTS), I removed it.

`macos-12` stay to allow for `x64` architecture prebuild (`macos-latest` will move to `arm64` in the future, so set the version explicitely)

2024-02-03 12:15 UTC, matthewkeil approved these changes
LGTM!! 🚀

2024-02-03 12:17 UTC, matthewkeil requested changes
Actually, just noticed that the specs are failing for some reason…. hmm

2024-02-03 16:03 UTC, jeluard commented
They now pass (after restarting them). I saw them passing before too.
For reference the error was:
```
  1) altair/eth_aggregate_pubkeys
       eth_aggregate_pubkeys_x40_pubkey:
     AssertionError: expected '0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' to deeply equal null
      at Context.<anonymous> (test/spec/index.test.ts:85:54)
      at processImmediate (node:internal/timers:478:21)
```

I am not clear how significant this is. Is it only on this specific platform? Or just a flaky test that also happen on other platforms?

It has to be noted that `darwin/arm64` users compiles this exact version (potential bu included) on their machine transparently when installing this lib (tests are not run then). So if there's an issue, the newly added `prebuild` merely surface it.

2024-02-03 16:49 UTC, matthewkeil approved these changes
> They now pass (after restarting them). I saw them passing before too. For reference the error was:
> 
> ```
>   1) altair/eth_aggregate_pubkeys
>        eth_aggregate_pubkeys_x40_pubkey:
>      AssertionError: expected '0xc00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' to deeply equal null
>       at Context.<anonymous> (test/spec/index.test.ts:85:54)
>       at processImmediate (node:internal/timers:478:21)
> ```
> 
> I am not clear how significant this is. Is it only on this specific platform? Or just a flaky test that also happen on other platforms?
> 
> It has to be noted that `darwin/arm64` users compiles this exact version (potential bu included) on their machine transparently when installing this lib (tests are not run then). So if there's an issue, the newly added `prebuild` merely surface it.

That is SUPER weird.... That seems VERY bad to have a spec fail randomly... sigh... there was nothing you did to make that though with this PR so gonna approve this but make a note of it to make sure that case is covered in the rebuild. I have addressed it in some versions but noticed it did not trigger sometimes without the added code for that condition and now know why.  double hmmm....

2024-02-03 16:52 UTC, matthewkeil commented
I am not sure of how we cut a release for this repo.  Have only been working on the rebuild stuff.  Do you want to sort through how to get this published after you merge @jeluard ?  I dont think we need to actually publish a new version but am not sure.  You can find the answer in the scripts dir where the binaries get downloaded.

2024-02-07 16:26 UTC, merged